trigger:
- master
pool:
  vmImage: "ubuntu-latest"
steps:
   - task: Gradle@2
     displayName: 'gradlew wrapper'
     inputs:
      gradleWrapperFile: android/gradlew.bat
      workingDirectory: android 
      tasks: wrapper
      options: '--gradle-version 6.3'
      publishJUnitResults: false

