trigger:
- master
pool:
  vmImage: "ubuntu-latest"
steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: '$(System.DefaultWorkingDirectory)/gradlew'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      tasks: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.html'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      sonarQubeRunAnalysis: false

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
      reportDirectory: '$(Build.SourcesDirectory)/build/reports/jacoco/test/html'