trigger:
- master
pool:
  vmImage: "windows-latest"
steps:

- task: GradleJacocoPackageUpdateTest@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: false
    options: '--stacktrace'
