trigger:
- master
pool:
  vmImage: "ubuntu-latest"
steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: '$(System.DefaultWorkingDirectory)/gradlew'
      options: '--gradle-version=6.3'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/customJacocoReportDir/TEST-*.html'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      sonarQubeRunAnalysis: false
