trigger:
- master
pool:
  vmImage: "ubuntu-latest"
steps:

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '--gradle-version 6.3'
    tasks: 'wrapper'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false