trigger:
- master
pool:
  vmImage: "ubuntu-latest"
steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: '$(System.DefaultWorkingDirectory)/gradlew'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      tasks: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.html'
      codeCoverageToolOption: 'JaCoCo'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      sonarQubeRunAnalysis: false