trigger:
- master
pool:
  vmImage: "windows-latest"
steps:
- task: JavaToolInstallerDTStest@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    cleanDestinationDirectory: false
- task: GradleTestCoverage@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: false
    options: '--stacktrace'
    codeCoverageToolOption: 'JaCoCo'
