trigger:
- master
pool:
  vmImage: "windows-latest"
steps:
- task: JavaToolInstallerDTStest@0
  inputs:
    versionSpec: '11'
    cleanDestinationDirectory: true

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
